name: 'Chromatic - Storybook Preview'

# The events that will trigger the action
on:
  # Trigger the workflow when a comment is created on an issue or pull request
  issue_comment:
    types: [created]
  # Allow the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  chromatic:
    # Only run the job if the comment contains '/storybook' OR it's triggered manually
    if: github.event_name == 'workflow_dispatch' || github.event.comment.body == '/storybook'
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          # Fetches all history so Chromatic can compare against previous builds
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          # Sets the version of Node.js to use
          node-version: 18

      - name: Install Dependencies
        run: yarn

      - name: Post Install
        run: yarn postinstall

      - name: Build
        run: yarn build:quick

      # Run Chromatic Action
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          # Chromatic projectToken, see https://storybook.js.org/tutorials/design-systems-for-developers/react/en/review/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/admin-ui

      # Create or update a comment on PR with the Storybook URL
      - name: Comment on PR with Storybook URL
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number || github.event.pull_request.number }}
          body: |
            🚀 **Storybook Preview**
            You can preview the Storybook by visiting the link below:

            [Storybook Preview URL](${{ steps.chromatic.outputs.storybookUrl }})
