# Name of our action
name: 'Chromatic - Storybook Preview'
# The event that will trigger the action
on:
  # Allow the workflow to be run manually
  workflow_dispatch:

# What the action will do
jobs:
  test:
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      - uses: actions/checkout@v2
        with:
          #👇 Fetches all history so Chromatic can compare against previous builds
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          #👇 Sets the version of Node.js to use
          node-version: 18
      - run: yarn
      - run: yarn postinstall
      - run: yarn build:quick
        #👇 Adds Chromatic as a step in the workflow
      - name: Run Chromatic
        id: chromatic
        uses: chromaui/action@v1
        # Options required for Chromatic's GitHub Action
        with:
          #👇 Chromatic projectToken, see https://storybook.js.org/tutorials/design-systems-for-developers/react/en/review/ to obtain it
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workingDir: packages/admin-ui
      # Create or update a comment on PR with the Storybook URL
      - name: Comment on PR with Storybook URL
        uses: peter-evans/create-or-update-comment@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            🚀 **Storybook Preview**
            You can preview the Storybook by visiting the link below:

            [Storybook Preview URL](${{ steps.chromatic.outputs.storybookUrl }})
