name: 'Check Commit Revision and Branch'

# The events that will trigger the action
on:
  # Trigger the workflow when a comment is created on an issue or pull request
  issue_comment:
    types: [created]
  # Allow the workflow to be run manually from the Actions tab
  workflow_dispatch:

jobs:
  checkbranch:
    # Only run the job if the comment contains '/storybook' OR it's triggered manually
    if: github.event_name == 'workflow_dispatch' || github.event.comment.body == '/branch'
    # The operating system it will run on
    runs-on: ubuntu-latest
    # The list of steps that the action will go through
    steps:
      # Step to print the GitHub context variables
      - name: Print GitHub context information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request Head SHA: ${{ github.event.pull_request.head.sha }}"
          echo "Ref Name: ${{ github.ref_name }}"
