name: 'Check Commit Revision and Branch'

on:
  issue_comment:
    types: [created]
  workflow_dispatch:

jobs:
  checkbranch:
    if: github.event.issue.pull_request && github.event.comment.body == '/branch'
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step to install hub
      - name: Install hub
        run: |
          sudo apt-get install -y hub

      # Step to fetch and print pull request details using hub
      - name: Get and Print Pull Request Details
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_number=${{ github.event.issue.number }}
          head_branch=$(hub pr show "$pr_number" -f '%H') # Head branch
          base_branch=$(hub pr show "$pr_number" -f '%B') # Base branch
          echo "Event Name: ${{ github.event_name }}"
          echo "Pull Request ref (head): $head_branch"
          echo "Pull Request ref (base): $base_branch"
          echo "Ref Name: ${{ github.ref_name }}"
